name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install dependencies (linux, macOS)
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        run: |
          pushd $HOME
          git clone --depth 1 https://github.com/facebook/buck.git
          cd buck
          ant
          popd
          echo "$HOME/buck/bin" >> $GITHUB_PATH
          export PATH=$PATH:$HOME/buck/bin/
          buck --version

      - name: Build
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        run: buck build //:yoga#default,shared

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: | 
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=cl.exe -A x64 ..
          cmake --build . -- /property:Configuration=Release

      - name: Release
        uses: justjavac/action-gh-push@v1
        if: |
          startsWith(github.repository, 'justjavac') &&
          github.ref == 'refs/heads/main' &&
          github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          repository: justjavac/yoga.dll
          files: |
            buck-out/gen/yoga#default,shared/libyogacore.dylib
            buck-out/gen/yoga#default,shared/libyogacore.so
            build/Release/yogacore.dll
